# Generated by Django 3.2.12 on 2022-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220411_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleruser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='scheduleruser',
            name='username',
            field=models.CharField(default='Username', max_length=60),
        ),
    ]
